GestorProducto1/Controllers/LoginController.cs
using GestorProductoBack.Model;
using GestorProductoBack.Repository;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using static GestorProductoBack.Model.GestorModel;

namespace GestorProducto1.Controllers
{
    public class LoginController : Controller
    {


        private InventarioDesarrolloWebEntities db = new InventarioDesarrolloWebEntities();
        GestorRepository<Usuario> data = new GestorRepository<Usuario>();
    
        // GET: Login
        public ActionResult Index(string cedula , string contra)
            {
            //ViewBag.Fecha = DateTime.Now.ToString("dd / MM / yyyy hh: mm:ss tt"); //se  setea la fecha

            if (string.IsNullOrEmpty(cedula) || string.IsNullOrEmpty(contra))
            {
                ViewBag.Error = "El usuario y la contraseña son obligatorios.";
                return View();
            }
            // Buscar al usuario en la base de datos
            var u = db.Usuario.FirstOrDefault(x => x.IdUsuario == cedula);
            if (u != null)
            {
                if(u.IdUsuario == cedula && u.Password == contra)
                {                
                        Session["usuario"] = u;
                    return RedirectToAction("Index", "Home");   
                }
            }
            ViewBag.mensaje = "Usuario o contraseña incorrecto";
           return View();            
        }
    }          
}

GestorProducto1/Controllers/RecuperarContraseñaController.cs
using GestorProductoBack.Model;
using GestorProductoBack.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;

namespace GestorProducto1.Controllers
{
    public class RecuperarContraseñaController : Controller
    {
        private InventarioDesarrolloWebEntities db = new InventarioDesarrolloWebEntities();
        GestorRepository<Usuario> data = new GestorRepository<Usuario>();
        // GET: RecuperarContraseña
        public ActionResult Index(string cedula, string contra, string contra1)
        {
            if (string.IsNullOrEmpty(cedula) || string.IsNullOrEmpty(contra) || string.IsNullOrEmpty(contra1))
            {
                ViewBag.Error = "Todos loc campos son obligatorios";
                return View();
            }

            // Buscar al usuario en la base de datos
            var u = db.Usuario.FirstOrDefault(x => x.IdUsuario == cedula);
            var c = db.Usuario.FirstOrDefault(x => x.Password == contra);

            if (u != null)
            {
                if (u.IdUsuario == cedula )
                {
                    
                    if(contra == contra1)
                    {
                        u.Password = contra1;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return RedirectToAction("Index", "Login");
                }
            }

            return View();
        }

        // GET: RecuperarContraseña/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RecuperarContraseña/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecuperarContraseña/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecuperarContraseña/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RecuperarContraseña/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecuperarContraseña/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RecuperarContraseña/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorProducto1/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAut.cshtml";
}


<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="~/Imagenes/loginAzul.png" />
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <br />
                <br />
                <br />

                <h6 id="reloj"> <p> Fecha y hora actual: </p>  @ViewBag.FechaHora</h6>
                <h3>  &nbsp;</h3>
                <h3>
                    <label>Bienvenido a Gestor inventario</label>
                </h3>
                <p>  &nbsp;</p>

                <!--form es una accion que redireccionara aun controlador-->

                <form method="post">

                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label" for="form3Example3">Usuario</label>
                        <input type="text" name="cedula" class="form-control form-control-lg" placeholder="usuario" />
                    </div>


                    <div data-mdb-input-init class="form-outline mb-3">
                        <label class="form-label" for="form3Example4">Contraseña </label>
                        <input type="password" name="contra" class="form-control form-control-lg" placeholder="contraseña" />
                    </div>

                    <div class="d-flex justify-content-between align-items-center">

                        <div class="form-check mb-0">
                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                            <label class="form-check-label" for="form2Example3">
                                Recordarme
                            </label>
                        </div>
                        <!-- <a fref="" class="text-body"> Olvidaste la contraseña?</a>    -->
                        @Html.ActionLink("¿Olvidaste la contraseña?", "Index", "RecuperarContraseña", null, new { @class = "text-body" })
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                    <asp:Label name="labelMensaje" runat="server" Text=""></asp:Label>
                    <br />
                    <br />
                    <h5>@ViewBag.mensaje</h5>

                </form>


            </div>
        </div>
        <br />
        <br />
        <br />
        <br />

        <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-secondary">

            <div class="text-white mb-3 mb-md-0">
                Gestor Inventario © 2025
               
                
                
                <script>
                    function actualizarReloj() {
                        const now = new Date();
                        document.getElementById("reloj").textContent = now.toLocaleString();
                    }
                    setInterval(actualizarReloj, 1000); // Actualiza cada segundo
                    actualizarReloj();
                </script>



            </div>
        </div>
    </div>
</section>